### ISSUE TITLE
Windows binary can't build because libgcc_s_dw2-1.dll is not installed

### ISSUE THREAD

**Issue by Qirky** [d0kt0r0/EspGrid#2]
Using Windows 8 and version 0.58.2 I get this error when running the installer binary. 

"The program can't start  because libgcc_s_dw2-1.dll is missing from your computer. Try reinstalling  the program to fix this problem"

Any suggestions?

**Comment by dktr0** [comment]
I am assuming you installed the required GNUStep stuff as per the instructions? If so, there is sometimes some weirdness with folders and paths that be can solved by launching the espgridd binary through the GNUstep terminal instead of (for instance) directly clicking on it some random place in the directory structure. If that doesn't solve it, maybe share with us the versions of the GNUstep installers you used and will investigate more.

**Comment by Qirky** [comment]
I don't think I had properly installed the GNUStep Core and seems to be working (or at least launching now). Thanks.
